myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"

urlpatterns = [
  path('', views.index, name="index"),
  path('verify', views.code_verify, name="code_verify"),
]

myproject/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

import myapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include("myapp.urls")),
]

myapp/models.py
from django.db import models

# Create your models here.
class InvitationCode(models.Model):
  code = models.CharField(verbose_name="Invitation Code", max_length=10, unique=True)
  expire = models.DateTimeField(verbose_name="Expire Time")
  
  def __str__(self):
    return self.code

myapp/forms.py
from django import forms
from .models import InvitationCode

class InvitationCodeForm(forms.ModelForm):
    class Meta:
        model = InvitationCode
        fields = ("code",)

myapp/views.py
from django.shortcuts import render, redirect
from .models import InvitationCode
from .forms import InvitationCodeForm
from django.utils.timezone import now
from django.contrib import messages

# Create your views here.
# Get client's IP address
def get_client_ip(request):
  x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
  if x_forwarded_for:
    ip = x_forwarded_for.split(',')[0]
  else:
    ip = request.META.get('REMOTE_ADDR')
  return ip


# Input invitation code, check the code, if right, redirect to the corresponding page
def index(request):
  session_key = "user_ip_{}".format(get_client_ip(request))
  # if user IP address is in session, and = TRUE, display hidden content
  if session_key in request.session and request.session[session_key]:
    return render(request, "myapp/index.html")
  else:
    form = InvitationCodeForm()
    return render(request, "myapp/index.html", {"form": form,})


# Verify user invitation code. Right invite code then set up session key as user IP, value=TRUE, conversation lasts for 60 seconds
def code_verify(request):
  session_key = "user_ip_{}".format(get_client_ip(request))
  if request.method == "POST":
    code = request.POST.get("code", "")
    code_obj = InvitationCode.objects.filter(code=code, expire__gt=now()).first()
    if code_obj:
      request.session[session_key] = True
      request.session.set_expiry(60) # Conversation valid for 60 seconds. Re-submit invite code after 60 seconds
      messages.success(request, 'You have a valid invitation code. This conversation will be valid for 60 seconds.')
    else:
      messages.warning(request, 'Your invite code is wrong or expired. Please try again.')
      if session_key in request.session:
        del request.session[session_key]

  return redirect("/")

myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django Session</title>
</head>
<body>
  <h2>You need invitation code to visit this page.</h2>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
 
  {% if form %}
  <form action="{% url 'myapp:code_verify' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
  </form>
  {% else %}
      <p>This part is hidden content. If you are able to view this part, you invite code is right and the session is still valid.</p>
  {% endif %}
  
</body>
</html>